version: '3'
services:
  pick_up_bot_redis:
    container_name: pick_up_bot_redis
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
        - '6380:6380'
    volumes:
        - './data:/bitnami/redis/data'  
  pick_up_bot:
    container_name: pick_up_bot
    build: .
    env_file: 
      - '.env'
    restart: always
    volumes: 
        - './data:/app/data'
        - './videos:/app/videos'
